---

environment_version: FOO
# User defined CIDR used for containers
# Global cidr/s used for everything.
cidr_networks:
  # Cidr used in the Management network
  container: 172.29.236.0/22
  # Cidr used in the Service network
  snet: 172.29.248.0/22
  # Cidr used in the VM network
  tunnel: 172.29.240.0/22
  # Cidr used in the Storage network
  storage: 172.29.244.0/22

global_overrides:
  internal_lb_vip_address: 10.51.50.1
  external_lb_vip_address: 10.51.50.1
  tunnel_bridge: "br-vxlan"
  container_bridge: "br-mgmt"
  # Define your neutron netowrks.
  neutron_provider_networks:
    - network:
        container_bridge: "br-vxlan"
        container_interface: "eth2"
        type: "vxlan"
        range: "1:1000"
        net_name: "vmnet"
    - network:
        container_bridge: "br-vlan"
        container_interface: "eth3"
        type: "flat"
        net_name: "extnet"
    - network:
        container_bridge: "br-vlan"
        container_interface: "eth3"
        type: "vlan"
        range: "1:1"
        net_name: "extnet"
infra_hosts:
  infra1:
    ip: 10.51.50.1

compute_hosts:
  infra1:
    ip: 10.51.50.1

storage_hosts:
  infra1:
    ip: 10.51.50.1
    # container_vars:
    #   cinder_backends:
    #     limit_container_types: cinder_volume
    #     lvm:
    #       volume_group: cinder-volumes
    #       driver: cinder.volume.drivers.lvm.LVMISCSIDriver
    #       backend_name: LVM_iSCSI

log_hosts:
  infra1:
    ip: 10.51.50.1

network_hosts:
  infra1:
    ip: 10.51.50.1

haproxy_hosts:
  infra1:
    ip: 10.51.50.1
